# .github/workflows/windows-msvc.yml
name: Windows MSVC (CMake)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg
        id: vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Force cloning vcpkg instead of expecting a ./vcpkg submodule
          vcpkgDirectory: ${{ runner.temp }}/vcpkg
          vcpkgGitURL: https://github.com/microsoft/vcpkg.git
          # IMPORTANT: put a real 40-char commit SHA here (not "master")
          vcpkgGitCommitId: 0000000000000000000000000000000000000000
          runVcpkgInstall: true   # runs 'vcpkg install' if vcpkg.json exists

      - name: Configure (CMake + vcpkg toolchain)
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: ball-windows
          path: build/*.exe
